project:
  type: website
  output-dir: _site

website:
  title: "Course Title"
  site-url: "https://giacomolemoli.github.io/fus-pol-course"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Slides"
        href: slides/week01.qmd
  page-footer:
    center: "Giacomo Lemoli · [giacomolemoli.github.io](https://giacomolemoli.github.io)"

format:
  html:
    theme: cosmo
    toc: true
