---
title: "Syllabus"
---

## Course Information
- Instructor: **Giacomo Lemoli** — [giacomolemoli.github.io](https://giacomolemoli.github.io)
- Instructor’s Email: [glemoli@fus.edu](mailto:glemoli@fus.edu)
- Office location: LAC 8 (3rd floor)
- Office Hours: Monday-Thursday 12:30-14:15
- Class location: Kaletsch Campus Bldg., Room 5
- Class meeting times: Monday-Thursday 14:30-15:45

## Course Description
This introductory course familiarizes students with the analytical tools used in Comparative Politics. It introduces key methodological and theoretical perspectives, defines and discusses major concepts and themes of comparative politics, introduces students to fundamental literature in the field, and allows students to analyze different case studies.

## Rationale
This course is a requirement for Political Science and International Relations majors.

## Course Goals
Upon completion of this course, students will be expected to:

- Demonstrate an ability to analyze domestic politics from a comparative perspective
- Define key terms used in the study of comparative politics
- Understand and be able to apply central theoretical approaches in comparative politics
- Be able to conduct basic comparative analyses thanks to methodological tools learned in class
- Be able to present, defend, and discuss results from the scientific literature in political science


## Specific Learning Outcomes
In this course, students will:

- Develop their knowledge of major political concepts and theories
- Cultivate their critical thinking skills
- Build strong analytical skills, particularly the ability to critically assess scientific articles, evaluate causal arguments, and conduct comparative analyses of countries
- Understand academic research (theoretical and empirical) in political science, unpack theories into their logical components and assess them critically
- Communicate clearly, precisely, and effectively to an audience


## Required Text and Materials
The course uses the following textbook:

- William R. Clark, Matt Golder, Sona N. Golder, **Foundations of Comparative Politics (2nd Edition)**. 2024, CQ Press

Two hard copies of the textbook are available in the Library. Alternatively, students can purchase the book in digital version (recommended) or paper version. 

In the review and discussion sessions, we will discuss scientific articles in comparative politics published in academic political science journals. The articles and other session-specific materials will be uploaded on Moodle.

## Assessment Overview

| **Assignment**                     | **Date Due** | **Midterm Weight** | **Final Weight** |
|------------------------------------|--------------|--------------------|------------------|
| Midterm exam (covering part I)     |              |        60%         |       30%        |
| Final Exam (covering part II)      |              |         0%         |       30%        |
| Paper presentation                 |              |         0%         |       20%        |
| Class participation                |              |        40%         |       20%        |



## Assessment Details

**Exams**. Two in-class, closed-book exams covering the two parts of the course.

**Paper presentation**. A 15-minute presentation and discussion of a scientific article.

A guide to a satisfactory, professional presentation will be provided.

**Class participation**.

Active participation is an important requisite of this course. You are expected to actively participate in the many discussions and group activities that we will have during the course. The participation grade crucially depends on your preparation for the class, especially the readings, and the quality of your contributions to the discussion.
Participation is distinct from attendance. Importantly, the assessment of students’ participation in discussion of political topics will be based on the quality of the students’ contributions to the class, their curiosity and critical thinking. The assessment will never be based on the level of agreement between a student and the instructor, or between a student and other students. 

See the Course Engagement rubric for evaluation criteria.

## Grading Policies and Expectations
Examinations are given letter grades according to the following numerical scale:

**A**: 94-100 

**A-**: 90-93 

**B+**: 88-89 

**B**: 84-87 

**B-**: 80-83 

**C+**: 78-79 

**C**: 74-77 

**C-**: 70-73 

**D+**: 68-69 

**D**: 64-67

**D-**: 60-63

**F**: 0-59

## How to Do Well in this Course (Policies/Requirements)

### Course structure and attendance

Every week will be devoted to one topic or module, and will have two sessions. The first session will cover the main concepts and current debates. These sessions will mostly follow the textbook.  The second session will consist of a review and discussion of the topic of the week. Here, students will apply the concepts seen in class to a variety of problems that will mimic those proposed in the midterm and final exams. Half of the time during the discussion sessions will be devoted to students' presentations of the academic articles, followed by a class discussion. Students will learn how theoretical concepts are developed and tested by political scientists in contemporary research.

Attendance in all sessions -- lectures and review/discussion -- is <u>necessary</u> (but not sufficient) to do well in the in-class exams and for participation.



### Readings

Students are <u>required</u> to read each session's materials <u>before</u> class. The discussion sessions, on which most of the participation grade is based, will <u>assume</u> that students have fully read the session materials and the textbook chapters of the week. Therefore, coming to class prepared is essential for the participation grade. 

### Absences

Students are permitted a maximum of 5 absences without penalty. This includes absences for medical reasons. Any further absences will lead to a reduction in the overall grade/participation grade and could lead to failing the course. 

Students with excessive absences may be reported to the Associate Dean for Student Success. 

Medical notes are only accepted where a student may miss an in-class evaluation (test, quiz, presentation etc.) and/or an assignment, or in cases of prolonged absence for documented medical reasons. Medical notes must relate to the specific date(s) of the absence. 

Students are also directed to the Catalog policy on Administrative Course Withdrawals.

### Course Engagement
Engagement includes active participation in and contribution to the course (not simply physical presence in the classroom), task completion, and overall approach to the course.

See the [Class Related Behavior Policy](https://fus.smartcatalogiq.com/current/academic-catalog/graduate-academic-policies-and-procedures/masters-level-academic-policies-and-procedures/classroom-behaviour-policy).

Student actively contribute to the course through:

- completing assigned tasks
- adhering to deadlines 
- posing relevant questions, either orally or in writing
- employing concrete examples, 
- integrating previous material, 
- providing thoughtful insights.


Course Engagement Rubric 

| **Grade** | **Course Engagement** |
|-----------|----------------------|
| A | Demonstrates consistent and constructive engagement (e.g. in-class activities, class discussions, collaborative work, responding to questions, online forums, and/or written responses). Contributions are thoughtful and well-prepared, pose relevant questions, employ concrete examples, integrate previous material, and provide meaningful insights while respecting others and not monopolizing discussion. |
| B | Demonstrates regular constructive (e.g. in-class activities, class discussions, collaborative work, responding to questions, online forums, and/or written responses). Contributions are generally relevant and prepared, refer to course readings where appropriate, and show developing insight, though they may be less detailed, less consistent, or more spontaneous than at the highest level. |
| C | Demonstrates some engagement (e.g. in-class activities, class discussions, collaborative work, responding to questions, online forums, and/or written responses) and/or often contributes only when prompted. Contributions tend to be brief, show minimal connection to course readings or course material, and may lack depth. May occasionally interrupt others or struggle to engage constructively. |
| D | Demonstrates little meaningful engagement (e.g. in-class activities, class discussions, collaborative work, responding to questions, online forums, and/or written responses). Contributions, when present, lack relevance and/or demonstrate little to no preparation. Behavior may be disruptive or disrespectful of others. |
| F | Demonstrates no meaningful engagement (e.g. in-class activities, class discussions, collaborative work, responding to questions, online forums, and/or written responses). Contributions, when present, demonstrate a lack of preparation, and behavior may be disruptive or disrespectful of others. |



## Diversity, Equity, & Inclusion in Our Classroom
Mutual respect is fundamental for any academic community like Franklin. At Franklin, each individual’s difference and uniqueness enrich our environment. Our shared values and beliefs lead us to respect all members of the community that we live in, and to value each other as individuals regardless of race, color, religion, gender identity or expression, sexual orientation, national or ethnic origin, genetics, age, or differences in ability. As members of the Franklin community, we support awareness of diversity, equity and inclusion through academic research, practical experiences and exchanges in everyday life.
All parties in the classroom space, including on class excursions and Academic Travel, are expected to:

- Show respect for all, valuing differences in identities, perspectives, and backgrounds;
- Engage in constructive dialogue that illustrates tolerance and respect for differing views and opinions;
- Contribute to a learning environment that ensures equal opportunities for all, avoiding any behavior that may marginalize or exclude others;
- Engage with course content and others in a culturally-aware manner, recognizing the impact of stereotypes, biases and assumptions.
Any form of discrimination, harassment, or disrespect based on identity will not be tolerated and should be reported immediately, either through the Bias Incident Reporting form on Moodle or by contacting the University-Wide Committee on Diversity, Equity and Inclusion at [dei@fus.edu](mailto:dei@fus.edu)

### Lived Name/Pronoun Syllabus Statement

I will gladly honor your request to address you by the name or gender pronoun that you choose.  I will provide the opportunity for you to indicate your choice on the first day of class so that I may make appropriate changes to my records, and I am always open to change. 


## Academic Integrity: Statement on Cheating and Plagiarism
A student whose actions are deemed by the University to be out of sympathy with the ideals, objectives or the spirit of good conduct as fostered by the University and Swiss community, may be placed on Disciplinary Probation or become subject to dismissal from the University. Cheating is a dishonest action out of sympathy with the ideals, objectives and spirit of the University. Furthermore, cheating reflects negatively on one’s personal integrity and is unjust to those students who have studied.

See the full statement [here](https://fus.smartcatalogiq.com/current/academic-catalog/undergraduate-academic-policies-and-procedures/academic-dishonesty-statement-on-cheating-and-plagiarism/) 

## Resources Available 
Students with certified learning differences are entitled to accommodations for all in-class activities, including, but not limited to, assessments. To ensure that both the learning objectives of the course and the needs of the student are upheld, a discussion of how a student’s accommodations will be implemented in the course must take place. In order to allow adequate time for implementation of appropriate accommodations, this discussion must be requested by the student within the first two weeks of the semester. In the case of a delayed diagnosis, this request must take place as soon as possible, and within two weeks of official notification from the Franklin Office of Accessibility Services.

The course instructor may require the student to sign a contract specifying related rights and responsibilities.

## Course Schedule 

See the full course schedule [here](schedule.qmd).


## Bibliography

See the full course schedule [here](schedule.qmd).